### ISSUE TITLE
KeyError: "post_process_steps" when running switch get_inputs

### ISSUE THREAD

**Issue by psernatorre** [RAEL-Berkeley/switch#119]
After entered "switch get_inputs" in the terminal, the data from database begins to copy to the input files: however, when it is copying to graph_config files, an error is showed as follows:

Running post processing...
Traceback (most recent call last):
  File "/data/home/psernatorre/switch/.switch/bin/switch", line 11, in <module>
    load_entry_point('switch-model', 'console_scripts', 'switch')()
  File "/data/home/psernatorre/switch/switch_model/__main__.py", line 70, in main
    cmds[args.subcommand]()
  File "/data/home/psernatorre/switch/switch_model/__main__.py", line 27, in runner
    importlib.import_module(module).main()
  File "/data/home/psernatorre/switch/switch_model/wecc/get_inputs/cli.py", line 76, in main
    for module in full_config["post_process_steps"]:
KeyError: 'post_process_steps' 

Despite the error, it is still possible to run the case.

**Comment by staadecker** [comment]
Seems like your missing `post_process_steps` in your config file. If you use the same format as `switch new scenario` (I think that's the command) it *should* work fine.

**Comment by staadecker** [comment]
closing since inactive
