### ISSUE TITLE
PermissionError when using get_inputs in new folder

### ISSUE THREAD

**Issue by pesap** [RAEL-Berkeley/switch#62]
@staadecker, found it while creating new inputs

```error
Traceback (most recent call last):
  File "/home/pesap/anaconda3/envs/switch-stable/bin/switch", line 33, in <module>
    sys.exit(load_entry_point('switch-model', 'console_scripts', 'switch')())
  File "/data/home/pesap/Dev/switch/switch_model/__main__.py", line 65, in main
    main()
  File "/data/home/pesap/Dev/switch/switch_model/wecc/get_inputs.py", line 163, in main
    post_process()
  File "/data/home/pesap/Dev/switch/switch_model/wecc/get_inputs.py", line 1042, in post_process
    shutil.copy(os.path.join(graph_config, "graph_tech_colors.csv"), "graph_tech_colors.csv")
  File "/home/pesap/anaconda3/envs/switch-stable/lib/python3.8/shutil.py", line 419, in copy
    copymode(src, dst, follow_symlinks=follow_symlinks)
  File "/home/pesap/anaconda3/envs/switch-stable/lib/python3.8/shutil.py", line 308, in copymode
    chmod_func(dst, stat.S_IMODE(st.st_mode))
PermissionError: [Errno 1] Operation not permitted: 'graph_tech_colors.csv'
```

It looks like permissions from the server to move files to that folder. Have you encountered this before? If not I wIll look into that.

cc @PatyHidalgo

**Comment by staadecker** [comment]
Haven't encountered before. It's supposed to copy from `switch_model.wecc.graph_config` but I'd make sure that it's actually trying to copy from that location

**Comment by staadecker** [comment]
@pesap closing since I haven't encountered this and you haven't mentioned it recently. If it's still an issue we can re-open
