### ISSUE TITLE
Bug on graphing tool

### ISSUE THREAD

**Issue by pesap** [RAEL-Berkeley/switch#85]
@staadecker , when running the current WECC branch this came out after the post-solve. It looks like there is a bug on how you call the run_graph_func. Below is the error.

```Python traceback
Traceback (most recent call last):
  File "/home/pesap/.local/bin/switch", line 11, in <module>
    load_entry_point('switch-model', 'console_scripts', 'switch')()
  File "/data/home/pesap/Dev/switch/switch_model/__main__.py", line 67, in main
    main()
  File "/data/home/pesap/Dev/switch/switch_model/solve.py", line 203, in main
    if instance.options.run_graph_func:
AttributeError: 'Namespace' object has no attribute 'run_graph_func'
```

**Comment by staadecker** [comment]
Fixed.
